name: Global Vars and Secrets

on:
  workflow_dispatch:

jobs:
  global-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Global Variables
        run: |
          echo "API URL: ${{ vars.API_URL }}"
          echo "DB URL: ${{ vars.DB_URL }}"

      - name: Use Global Secrets
        run: |
          echo "Using Global API Key: $DB_PASSWORD"
        env:
          GLOBAL_API_KEY: ${{ secrets.DB_PASSWORD }}
